### ISSUE TITLE
DownloadTask doesn't use the `/v1` suffix to form the URL

### ISSUE THREAD

**Issue by arumoy** [swagger-api/swaggerhub-gradle-plugin#29]
The [documentation](https://support.smartbear.com/swaggerhub/docs/apis/downloading-swagger-definition.html) says that an API visible at `http(s)://{swaggerhub-host}/apis/{owner}/{api}/{version}` will be downloadable at `http(s)://{swaggerhub-host}/v1/apis/{owner}/{api}/{version}` &mdash;

> In SwaggerHub On-Premise:
> http(s)://{swaggerhub-host}/v1/apis/{owner}/{api}/{version}?resolved=true

But the DownloadTask gets me the output of an HTML, which is same as skipping the **/v1** part in the URL.

**Comment by arumoy** [comment]
Submitted a PR here &mdash; #30. Please review!

**Comment by barryadk** [comment]
Thanks @arumoy!

**Comment by arumoy** [comment]
Thanks a bunch, @barryadk for your time.
Is there a public release schedule that I can anticipate, if it's not SmartBear-internal material?

**Comment by barryadk** [comment]
I've released version `1.3.0` which includes your change:
https://github.com/swagger-api/swaggerhub-gradle-plugin/releases/tag/1.3.0
https://plugins.gradle.org/plugin/io.swagger.swaggerhub/1.3.0

Thanks again for your contribution.
